export const MainSliderData = [
	
	{
		id: 1,
		layout:'type2',
		bgimg_lg_jpg: '/images/main-slider/slide01.png',
		bgimg_lg_webp: '/images/main-slider/slide01.png',
		bgimg_md_jpg: '/images/main-slider/slide01.png',
		bgimg_md_webp: '/images/main-slider/slide01.png',
		bgimg_sm_jpg: '/images/main-slider/slide01.png',
		bgimg_sm_webp: '/images/main-slider/slide01.png',
		
		title: `Your Dream, Our Commitment`,
		text: `Whether you want to renovate or new build, we're here to help.`,
	},
	{
		id: 2,
		layout:'type2',
		bgimg_lg_jpg: '/images/main-slider/slide02.png',
		bgimg_lg_webp: '/images/main-slider/slide02.png',
		bgimg_md_jpg: '/images/main-slider/slide02.png',
		bgimg_md_webp: '/images/main-slider/slide02.png',
		bgimg_sm_jpg: '/images/main-slider/slide02.png',
		bgimg_sm_webp: '/images/main-slider/slide02.png',
		title: `Complete Kitchen Renovations in Sydney`,
		text: `Dedicated to delivering innovative kitchen designs and renovation solutions. Contact us today for a quote or visit our showroom to explore our offerings.`,
	},
	{
		id: 3,
		layout:'type2',
		bgimg_lg_jpg: '/images/main-slider/slide06.png',
		bgimg_lg_webp: '/images/main-slider/slide06.png',
		bgimg_md_jpg: '/images/main-slider/slide06.png',
		bgimg_md_webp: '/images/main-slider/slide06.png',
		bgimg_sm_jpg: '/images/main-slider/slide06.png',
		bgimg_sm_webp: '/images/main-slider/slide06.png',
		title: `Custom Wardrobes Sydney`,
		text: `Our designers will help you maximise your space while incorporating unique design elements, making your daily tasks more practical and effortless.`,
	},
	{
		id: 4,
		layout:'type2',
		bgimg_lg_jpg: '/images/main-slider/slide03.png',
		bgimg_lg_webp: '/images/main-slider/slide03.png',
		bgimg_md_jpg: '/images/main-slider/slide03.png',
		bgimg_md_webp: '/images/main-slider/slide03.png',
		bgimg_sm_jpg: '/images/main-slider/slide03.png',
		bgimg_sm_webp: '/images/main-slider/slide03.png',
		title: `Custom Bathroom Renovations in Sydney`,
		text: `Unlock the beauty and functionality of your bathroom today. Call us for a free quote and let us bring your dream bathroom to life.`,
	},
	{
		id: 5,
		layout:'type2',
		bgimg_lg_jpg: '/images/main-slider/slide04.png',
		bgimg_lg_webp: '/images/main-slider/slide04.png',
		bgimg_md_jpg: '/images/main-slider/slide04.png',
		bgimg_md_webp: '/images/main-slider/slide04.png',
		bgimg_sm_jpg: '/images/main-slider/slide04.png',
		bgimg_sm_webp: '/images/main-slider/slide04.png',
		title: `Laundry Designs and Renovations in Sydney`,
		text: `We carefully consider every feature to optimise your laundry design, offering cost-effective solutions that are modern and aesthetically beautiful.`,
	},
	{
		id: 5,
		layout:'type2',
		bgimg_lg_jpg: '/images/main-slider/slide05.png',
		bgimg_lg_webp: '/images/main-slider/slide05.png',
		bgimg_md_jpg: '/images/main-slider/slide05.png',
		bgimg_md_webp: '/images/main-slider/slide05.png',
		bgimg_sm_jpg: '/images/main-slider/slide05.png',
		bgimg_sm_webp: '/images/main-slider/slide05.png',
		title: `Mirror Supplies`,
		text: `We meticulously consider each aspect of your laundry design, delivering modern, visually stunning, and cost-effective renovation solutions.`,
	},
];
